In [17]:
# !pip install numpy
# Load Numpy
import numpy as np


# The basics

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Dimension
a.ndim

1

In [12]:
# get Shape
b.shape

(2, 3)

In [14]:
# get type | int32 by default
a.dtype

dtype('int32')

In [15]:
#get size
a.itemsize

4

In [16]:
# Get total size
a.size * a.itemsize

12

In [19]:
#fcc question
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


# Accessing / Changing specific elements, rows, columns, etc

In [21]:
# 2D array

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get a specific element [row, column]
a[1, 5]

# negative notation can be used as well.
a[1, -2]

13

In [26]:
# Get a specific row | use slice syntax
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [28]:
# Getting a little more fancy [startindext:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [30]:
# Replacing a value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [32]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3D Example

In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# Get a specific element of 3D Example(work outside in)
# Let's say I wanted 4.
b[0,1,1]

4

In [43]:
# replace only if it's the same dimension
b[:,1,:] = [[9,9],[8,8]]

In [44]:
b

array([[[9, 9],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [53]:
# FCC Question 
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
a[:, 2] = 20
a

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])

# Initializing Different Types of Arrays

In [56]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
# 2D matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
# 3d Matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [59]:
# 4d Matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [60]:
# All 1s matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
# Any other number matrix
# Ex: 2x2 Matrix using 99
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [63]:
# Any other number (full_like) method
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [66]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.71895398, 0.80674622],
       [0.50814609, 0.09429083],
       [0.64932831, 0.16856823],
       [0.39746776, 0.45834466]])

In [71]:
# random interger values
np.random.randint(9, size=(3,3))

array([[4, 2, 1],
       [5, 3, 6],
       [8, 8, 3]])

In [72]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [74]:
# Free Code Camp question
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


# Initialize Array Problem

In [84]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1:1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z
print(output)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [93]:
#### Be careful when copying arrays!!!!

a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
print(b)

[ 1  2 20  4  5]


# Mathematics

In [94]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [95]:
a + 2

array([3, 4, 5, 6])

In [96]:
a - 2

array([-1,  0,  1,  2])

In [97]:
a * 2

array([2, 4, 6, 8])

In [98]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [99]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [100]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [101]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [103]:
# For more on routines: https://numpy.org/doc/stable/reference/routines.array-creation.html

# Linear Algebra

In [106]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [108]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [109]:
# For more info: https://numpy.org/doc/stable/reference/routines.linalg.html

# Determinant
# Trace
# Singualr Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc....

# Statistics

In [110]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.min(stats)

1

In [112]:
np.max(stats)

6

In [115]:
np.min(stats, axis=1)

array([1, 4])

In [117]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [120]:
# Fcc Question
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()

print(b)

15


# Reoganizing Arrays


In [122]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [123]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [125]:
# fcc question challenge 
a = np.ones((2, 4))
b = a.reshape((4, 2))
print(b)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# Misc

In [129]:
# loading data from file
filedata = np.genfromtxt('data.txt', delimiter =',')
filedata

array([[ 1.,  3.,  5.,  7.,  9., 11.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.]])

In [130]:
filedata.astype('int32')

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18]])

In [132]:
## Boolean masking and Advanced Indexing

filedata > 50

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [134]:
filedata[filedata > 50]

array([], dtype=float64)

In [136]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [137]:
(filedata > 50 ) & (filedata < 100)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [140]:
#Fcc question

filedata = np.genfromtxt('data2.txt', delimiter=',')
output = filedata[filedata < 50]

print(output)

[29. 32. 45. 15.  5. 22.]
